[pytest]
testpaths = tests
addopts = --cov=app --cov-report=term-missing --cov-config=pytest.ini

[coverage:run]
omit =
    app/controllers/*
    app/main.py
    app/repositories/factura_repository.py
    app/repositories/reporte_repository.py
    app/services/factura_service.py
    app/services/reporte_service.py
    app/schemas/factura_schema.py
    app/schemas/reporte_schema.py
